name: Publish Docs
on:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/base
      - name: Build
        uses: ./.github/workflows/build
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Deploy Docs
        uses: ./.github/workflows/docs
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}